format indent

diff --git a/linux_doc_words_counter b/linux_doc_words_counter
--- a/linux_doc_words_counter
+++ b/linux_doc_words_counter
@@ -18,15 +18,15 @@
 #   - sudo privileges
 #	- unzip package
 #	- catdoc package
-#	
-# AUTHOR: 
+#
+# AUTHOR:
 #	linux_doc_words_counter is written by Alfio Salanitri <www.alfiosalanitri.it> and are licensed under the terms of the GNU General Public License, version 2 or higher.
-# 
-# 
+#
+#
 #############################################################
-# Icons	and color	
+# Icons	and color
 # https://www.techpaste.com/2012/11/print-colored-text-background-shell-script-linux/
-# https://apps.timwhitlock.info/emoji/tables/unicode		#
+# https://apps.timwhitlock.info/emoji/tables/unicode
 #############################################################
 red='\033[0;31m'
 green='\033[0;32m'
@@ -35,51 +35,52 @@ icon_ko='\xe2\x9c\x97'
 icon_wait='\xE2\x8C\x9B'
 
 #############################################################
-# Sudo password         									#
+# Sudo password
 #############################################################
 sudo printf "${icon_wait} Wait please...\n"
 
 #############################################################
-# Check Dependencies										#
+# Check Dependencies
 #############################################################
 # Check unzip
-if ! command -v unzip &> /dev/null; then
-	printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}unzip${nocolor} is required. sudo apt install unzip\n"
-	exit 1;
+if ! command -v unzip &>/dev/null; then
+  printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}unzip${nocolor} is required. sudo apt install unzip\n"
+  exit 1
 fi
 # Check catdoc
-if ! command -v catdoc &> /dev/null; then
-	printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}catdoc${nocolor} is required. sudo apt install catdoc\n"
-	exit 1;
+if ! command -v catdoc &>/dev/null; then
+  printf "[${red}${icon_ko}${nocolor}] Sorry, but ${green}catdoc${nocolor} is required. sudo apt install catdoc\n"
+  exit 1
 fi
 
 #############################################################
-# Check Required variables									#
+# Check Required variables
 #############################################################
 if [ ! -f "$1" ]; then
-    printf "[${red}${icon_ko}${nocolor}] Type the zip file (full path).\n";
-    exit 1;
+  printf "[${red}${icon_ko}${nocolor}] Type the zip file (full path).\n"
+  exit 1
 fi
 
 #############################################################
-# Start									#
+# Start
 #############################################################
 filezip=$1
 
 # check zip integrity
 if [ -z "$(unzip -t $filezip | grep "No errors detected")" ]; then
-    printf "[${red}${icon_ko}${nocolor}] The $filezip file isnt't a valid zip archive.\n";
-    exit 1;
+  printf "[${red}${icon_ko}${nocolor}] The $filezip file isnt't a valid zip archive.\n"
+  exit 1
 fi
 
 # create temp dir
 temp_dir=$(mktemp -d -t doc-word-character-counter-XXXXXXXXXX)
 
 # unzip archive
-unzip -j $filezip -d $temp_dir > /dev/null 2>&1
+unzip -j $filezip -d $temp_dir >/dev/null 2>&1
 
 # go to temp
-cd $temp_dir;
+# shellcheck disable=SC2164
+cd $temp_dir
 
 # store current dir
 current_directory=$(pwd)
@@ -88,27 +89,28 @@ current_directory=$(pwd)
 mkdir txt
 
 # convert .doc files to txt if exists
-for file in *.doc ; do 
-    if [ -f "${current_directory}/$file" ]; then
-        sudo catdoc "${current_directory}/$file" > "${current_directory}/txt/${file}.txt"
-    fi
+for file in *.doc; do
+  if [ -f "${current_directory}/$file" ]; then
+    sudo catdoc "${current_directory}/$file" >"${current_directory}/txt/${file}.txt"
+  fi
 done
 
 # mv all .txt files
 mv *.txt "${current_directory}/txt/"
 
 # go to txt dir
+# shellcheck disable=SC2164
 cd txt
 
 # print output
 printf "\e[4mWords\e[0m\t\t\e[4mCharacters\e[0m\t\e[4mFile\e[0m\n"
 # save each line in the results.txt
-for file in *.txt ; do 
-    words=$(wc -wc "$file" | awk '{ print $1}')
-    characters=$(wc -wc "$file" | awk '{ print $2 }')
-    name=$(echo "$file" | sed 's/\s\+/-/g')
-    printf "%s\t\t%s\t\t'%s'\n" "$words" "$characters" "$name"
-done | column -t -s "$" > results.txt
+for file in *.txt; do
+  words=$(wc -wc "$file" | awk '{ print $1}')
+  characters=$(wc -wc "$file" | awk '{ print $2 }')
+  name=$(echo "$file" | sed 's/\s\+/-/g')
+  printf "%s\t\t%s\t\t'%s'\n" "$words" "$characters" "$name"
+done | column -t -s "$" >results.txt
 cat results.txt
 echo "-------------------------------------------------------"
 printf "${green}Total words:${nocolor} %d\n" $(awk '{s+=$1} END {print s}' results.txt)
